name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: |
        go get -v github.com/onsi/ginkgo/ginkgo
        go get -v github.com/onsi/gomega
        go get -v -t ./...
        export PATH=$PATH:$HOME/gopath/bin

#     - name: Build
#       run: go build -v ./...

    - name: Ginkgo Test
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
        ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2
        ./cc-test-reporter after-build -t gocov -p $(go list -m)
      
      env:
        CC_TEST_REPORTER_ID: ca2c58a85fab8ac43b248334cbd311aec9b4cca3d00c2e9057a334e9e5d39bcb
