name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install dependencies
      run: |
        go get -v -t ./...
        export PATH=$PATH:$HOME/gopath/bin

    - name: Test
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
        go test -v -coverpkg ./src/... ./tests/... -coverprofile="c.out"
        go tool cover -func c.out
        ./cc-test-reporter after-build -t gocov -p $(go list -m)
      
      env:
        CC_TEST_REPORTER_ID: ca2c58a85fab8ac43b248334cbd311aec9b4cca3d00c2e9057a334e9e5d39bcb
