name: Go

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: |
        go get -v -t ./...
        export PATH=$PATH:$HOME/gopath/bin

    - name: Test
      run: |
        go test -v -coverpkg ./src/... ./tests/... -coverprofile="c.out"
        go tool cover -func c.out

    - name: Build
      run: go build -v ./...